import { Expense, PaymentMethod } from "@/interfaces/Expense";
import { create } from "zustand";

interface ExpenseStore {
  expenses: Expense[];
  addExpense: (expense: Omit<Expense, "id"> & { id?: string }) => void;
  removeExpense: (id: string) => void;
  updateExpense: (updatedExpense: Expense) => void;
  setExpenses: (expenses: Expense[]) => void;
}

export const initialExpenses: Expense[] = [
  {
    id: "1",
    category: "Housing",
    name: "Aluguel Apartamento",
    description: "Aluguel mensal",
    date: new Date("2026-05-01"),
    duePaymentDate: new Date("2026-05-05"),
    totalPrice: 1850,
    installments: 1,
    isPaid: true,
    merchant: "Imobiliária Central",
    payments: [
      {
        id: 101,
        amount: 1850,
        paymentDate: new Date("2026-05-03"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.PIX,
      },
    ],
    tags: ["essential", "monthly"],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-03"),
  },
  {
    id: "2",
    category: "Shopping",
    name: "Tênis Nike Air Max",
    date: new Date("2026-05-10"),
    duePaymentDate: new Date("2026-05-10"),
    totalPrice: 679.9,
    installments: 6,
    isPaid: false,
    merchant: "Nike Store",
    payments: [
      {
        id: 201,
        amount: 113.32,
        paymentDate: new Date("2026-05-10"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
      {
        id: 202,
        amount: 113.32,
        paymentDate: new Date("2026-06-10"),
        monthReference: "2026-06",
        installmentNumber: 2,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
    ],
    tags: ["personal"],
    createdAt: new Date("2026-05-10"),
    updatedAt: new Date("2026-06-10"),
  },
  {
    id: "3",
    category: "Food",
    name: "Compras no Supermercado Curitibaaaaaaaaa",
    date: new Date("2026-05-12"),
    duePaymentDate: new Date("2026-05-12"),
    totalPrice: 523.45,
    installments: 1,
    isPaid: true,
    merchant: "Extra Hipermercado",
    payments: [
      {
        id: 301,
        amount: 523.45,
        paymentDate: new Date("2026-05-12"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.DEBIT_CARD,
      },
    ],
    tags: ["groceries"],
    createdAt: new Date("2026-05-12"),
    updatedAt: new Date("2026-05-12"),
  },
  {
    id: "4",
    category: "Utilities",
    name: "Conta de Luz",
    date: new Date("2026-05-05"),
    duePaymentDate: new Date("2026-05-15"),
    totalPrice: 142.78,
    installments: 1,
    isPaid: false,
    merchant: "Copel",
    payments: [],
    tags: ["essential", "monthly"],
    createdAt: new Date("2026-05-05"),
    updatedAt: new Date("2026-05-05"),
  },
  {
    id: "5",
    category: "Entertainment",
    name: "Netflix + Disney+",
    date: new Date("2026-05-02"),
    duePaymentDate: new Date("2026-05-02"),
    totalPrice: 79.9,
    installments: 1,
    isPaid: true,
    merchant: "Netflix",
    payments: [
      {
        id: 501,
        amount: 79.9,
        paymentDate: new Date("2026-05-01"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
    ],
    tags: ["subscription", "monthly"],
    createdAt: new Date("2026-05-01"),
    updatedAt: new Date("2026-05-02"),
  },
  {
    id: "6",
    category: "Health",
    name: "Consulta + Exames",
    description: "Cardiologista + hemograma",
    date: new Date("2026-05-08"),
    duePaymentDate: new Date("2026-05-20"),
    totalPrice: 485,
    installments: 3,
    isPaid: false,
    merchant: "Clínica Santa Luzia",
    payments: [
      {
        id: 601,
        amount: 161.67,
        paymentDate: new Date("2026-05-15"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.PIX,
      },
    ],
    tags: ["health"],
    createdAt: new Date("2026-05-08"),
    updatedAt: new Date("2026-05-15"),
  },
  {
    id: "7",
    category: "Transport",
    name: "Manutenção do Carro",
    description: "Revisão + troca de óleo",
    date: new Date("2026-05-18"),
    duePaymentDate: new Date("2026-05-18"),
    totalPrice: 680,
    installments: 2,
    isPaid: true,
    merchant: "Oficina Mecânica Rápida",
    payments: [
      {
        id: 701,
        amount: 340,
        paymentDate: new Date("2026-05-18"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.PIX,
      },
      {
        id: 702,
        amount: 340,
        paymentDate: new Date("2026-06-10"),
        monthReference: "2026-06",
        installmentNumber: 2,
        paymentMethod: PaymentMethod.PIX,
      },
    ],
    tags: ["car"],
    createdAt: new Date("2026-05-18"),
    updatedAt: new Date("2026-06-10"),
  },
  {
    id: "8",
    category: "Education",
    name: "Curso de Inglês - Mensalidade",
    date: new Date("2026-05-01"),
    duePaymentDate: new Date("2026-05-05"),
    totalPrice: 890,
    installments: 12,
    isPaid: false,
    merchant: "Wizard Idiomas",
    payments: [
      {
        id: 801,
        amount: 74.17,
        paymentDate: new Date("2026-05-03"),
        monthReference: "2026-05",
        installmentNumber: 2,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
    ],
    tags: ["education", "monthly"],
    createdAt: new Date("2026-04-20"),
    updatedAt: new Date("2026-05-03"),
  },
  {
    id: "9",
    category: "Food",
    name: "Jantar Romântico",
    description: "Aniversário de namoro",
    date: new Date("2026-05-22"),
    duePaymentDate: new Date("2026-05-22"),
    totalPrice: 245.8,
    installments: 1,
    isPaid: true,
    merchant: "Restaurante Vila Italiana",
    payments: [
      {
        id: 901,
        amount: 245.8,
        paymentDate: new Date("2026-05-22"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.PIX,
      },
    ],
    tags: ["date", "food"],
    createdAt: new Date("2026-05-22"),
    updatedAt: new Date("2026-05-22"),
  },
  {
    id: "10",
    category: "Travel",
    name: "Passagem Curitiba → Florianópolis",
    date: new Date("2026-05-25"),
    duePaymentDate: new Date("2026-06-25"),
    totalPrice: 1240,
    installments: 4,
    isPaid: false,
    merchant: "Gol Linhas Aéreas",
    payments: [
      {
        id: 1001,
        amount: 310,
        paymentDate: new Date("2026-05-25"),
        monthReference: "2026-05",
        installmentNumber: 1,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
      {
        id: 1002,
        amount: 310,
        paymentDate: new Date("2026-06-20"),
        monthReference: "2026-06",
        installmentNumber: 2,
        paymentMethod: PaymentMethod.CREDIT_CARD,
      },
    ],
    tags: ["travel", "vacation"],
    createdAt: new Date("2026-05-20"),
    updatedAt: new Date("2026-06-20"),
  },
];

export const useExpenseStore = create<ExpenseStore>((set) => ({
  expenses: initialExpenses,
  addExpense: (expense) =>
    set((state) => ({
      expenses: [
        ...state.expenses,
        {
          ...expense,
          id: expense.id ?? String(Date.now()),
        },
      ],
    })),
  removeExpense: (id) =>
    set((state) => ({
      expenses: state.expenses.filter((el) => el.id !== id),
    })),
  updateExpense: (updatedExpense) =>
    set((state) => ({
      expenses: state.expenses.map((el) => (el.id === updatedExpense.id ? updatedExpense : el)),
    })),
  setExpenses: (expenses) => set({ expenses }),
}));
